# Generated by Django 5.2.4 on 2025-09-08 09:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmissionFactor',
            fields=[
                ('factor_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Descriptive name of the emission factor', max_length=255)),
                ('category', models.CharField(choices=[('fuel_combustion', 'Fuel Combustion'), ('company_vehicles', 'Company-Owned Vehicles'), ('refrigerants_fugitive', 'Refrigerants & Fugitive Emissions'), ('process_emissions', 'Industrial Process Emissions'), ('electricity_consumption', 'Electricity Consumption'), ('purchased_steam_heat_cooling', 'Purchased Steam/Heat/Cooling'), ('purchased_goods_materials', 'Purchased Goods & Materials (Cat 1)'), ('capital_goods', 'Capital Goods (Cat 2)'), ('fuel_energy_related', 'Fuel & Energy Related Activities (Cat 3)'), ('upstream_transport', 'Upstream Transportation & Distribution (Cat 4)'), ('waste_generated', 'Waste Generated in Operations (Cat 5)'), ('business_travel', 'Business Travel (Cat 6)'), ('employee_commuting', 'Employee Commuting (Cat 7)'), ('upstream_leased_assets', 'Upstream Leased Assets (Cat 8)'), ('downstream_transport', 'Downstream Transportation & Distribution (Cat 9)'), ('processing_sold_products', 'Processing of Sold Products (Cat 10)'), ('use_sold_products', 'Use of Sold Products (Cat 11)'), ('end_of_life_sold_products', 'End-of-Life Treatment of Sold Products (Cat 12)'), ('downstream_leased_assets', 'Downstream Leased Assets (Cat 13)'), ('franchises', 'Franchises (Cat 14)'), ('investments', 'Investments (Cat 15)'), ('water_supply_treatment', 'Water Supply & Treatment'), ('spend_based_fallback', 'Spend-Based Calculation')], help_text='GHG Protocol category', max_length=50)),
                ('emission_factor_value', models.DecimalField(decimal_places=6, help_text='Emission factor value in kgCO₂e per unit', max_digits=20)),
                ('unit', models.CharField(help_text='Unit of measurement (validated against category)', max_length=50)),
                ('source', models.CharField(help_text='Data source or reference', max_length=200)),
                ('year', models.IntegerField(help_text='Year of publication or applicability')),
                ('description', models.TextField(blank=True, help_text='Additional notes or context', null=True)),
                ('sub_category', models.CharField(blank=True, help_text='More specific categorization', max_length=100, null=True)),
                ('entry_type', models.CharField(choices=[('simple', 'Simple Entry'), ('guided', 'Guided Entry')], default='simple', help_text='How this factor was entered (simple or guided)', max_length=10)),
                ('guided_parameters', models.JSONField(blank=True, help_text='Additional parameters captured during guided entry', null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'name'],
                'indexes': [models.Index(fields=['category'], name='api_emissio_categor_6fa7ec_idx'), models.Index(fields=['year'], name='api_emissio_year_854ebf_idx'), models.Index(fields=['source'], name='api_emissio_source_1b4580_idx')],
            },
        ),
        migrations.CreateModel(
            name='LCAProduct',
            fields=[
                ('lca_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('functional_unit', models.CharField(max_length=255)),
                ('total_carbon_footprint_per_unit', models.DecimalField(decimal_places=6, default=0, max_digits=15)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lca_products', to='api.project')),
            ],
        ),
        migrations.CreateModel(
            name='EmissionScope',
            fields=[
                ('scope_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope_number', models.IntegerField(choices=[(1, 'Scope 1'), (2, 'Scope 2'), (3, 'Scope 3')])),
                ('total_emissions_tco2e', models.DecimalField(decimal_places=6, default=0, max_digits=15)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to='api.project')),
            ],
            options={
                'unique_together': {('project', 'scope_number')},
            },
        ),
        migrations.CreateModel(
            name='EmissionActivity',
            fields=[
                ('activity_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=15)),
                ('unit', models.CharField(max_length=50)),
                ('scope3_category', models.CharField(blank=True, choices=[('purchased_goods_services', '1. Purchased goods and services'), ('capital_goods', '2. Capital goods'), ('fuel_energy_related', '3. Fuel- and energy-related activities'), ('upstream_transport', '4. Upstream transportation and distribution'), ('waste_generated', '5. Waste generated in operations'), ('business_travel', '6. Business travel'), ('employee_commuting', '7. Employee commuting'), ('leased_assets_upstream', '8. Upstream leased assets'), ('downstream_transport', '9. Downstream transportation and distribution'), ('processing_sold_products', '10. Processing of sold products'), ('use_sold_products', '11. Use of sold products'), ('end_of_life', '12. End-of-life treatment of sold products'), ('leased_assets_downstream', '13. Downstream leased assets'), ('franchises', '14. Franchises'), ('investments', '15. Investments')], max_length=64, null=True)),
                ('calculated_emissions', models.DecimalField(decimal_places=6, default=0, max_digits=15)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('emission_factor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='api.emissionfactor')),
                ('scope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='api.emissionscope')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='api.project')),
            ],
        ),
    ]
