# Generated by Django 5.2.4 on 2025-11-18 17:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LCAActivity',
            fields=[
                ('activity_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_name', models.CharField(help_text='User-friendly name for this activity', max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('bw2_database', models.CharField(help_text="Brightway2 database name (e.g., 'ecoinvent-3.9.1-cutoff')", max_length=255)),
                ('bw2_activity_code', models.CharField(help_text='Brightway2 activity code', max_length=255)),
                ('bw2_activity_name', models.CharField(blank=True, help_text='Cached name from Brightway2', max_length=500, null=True)),
                ('bw2_location', models.CharField(blank=True, help_text='Cached location from Brightway2', max_length=100, null=True)),
                ('bw2_unit', models.CharField(blank=True, help_text='Cached unit from Brightway2', max_length=50, null=True)),
                ('quantity', models.DecimalField(decimal_places=6, help_text='Amount of the activity', max_digits=15)),
                ('impact_method', models.JSONField(blank=True, default=dict, help_text="Impact assessment method as tuple, e.g., ('IPCC 2013', 'climate change', 'GWP 100a')")),
                ('calculated_emissions', models.DecimalField(decimal_places=6, default=0, help_text='Calculated emissions in kgCO₂e (will be converted to tCO₂e for display)', max_digits=15)),
                ('scope3_category', models.CharField(blank=True, choices=[('purchased_goods_services', '1. Purchased goods and services'), ('capital_goods', '2. Capital goods'), ('fuel_energy_related', '3. Fuel- and energy-related activities'), ('upstream_transport', '4. Upstream transportation and distribution'), ('waste_generated', '5. Waste generated in operations'), ('business_travel', '6. Business travel'), ('employee_commuting', '7. Employee commuting'), ('leased_assets_upstream', '8. Upstream leased assets'), ('downstream_transport', '9. Downstream transportation and distribution'), ('processing_sold_products', '10. Processing of sold products'), ('use_sold_products', '11. Use of sold products'), ('end_of_life', '12. End-of-life treatment of sold products'), ('leased_assets_downstream', '13. Downstream leased assets'), ('franchises', '14. Franchises'), ('investments', '15. Investments')], max_length=64, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('last_calculated', models.DateTimeField(blank=True, help_text='When LCA calculation was last performed', null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lca_activities', to='api.project')),
                ('scope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lca_activities', to='api.emissionscope')),
            ],
            options={
                'verbose_name': 'LCA Activity',
                'verbose_name_plural': 'LCA Activities',
                'ordering': ['-created_date'],
            },
        ),
    ]
