# Generated by Django 5.2.4 on 2025-09-09 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emissionfactor',
            name='entry_type',
        ),
        migrations.RemoveField(
            model_name='emissionfactor',
            name='guided_parameters',
        ),
        migrations.AddField(
            model_name='emissionfactor',
            name='uncertainty_params',
            field=models.JSONField(blank=True, help_text="Statistical distribution parameters (e.g., {'mean': x, 'sigma': y, 'min': z, 'max': w})", null=True),
        ),
        migrations.AddField(
            model_name='emissionfactor',
            name='uncertainty_type',
            field=models.IntegerField(choices=[(0, 'No uncertainty'), (1, 'Lognormal'), (2, 'Normal'), (3, 'Uniform'), (4, 'Triangular'), (5, 'Beta')], default=0, help_text='Statistical distribution type for uncertainty analysis (Brightway2 conventions)'),
        ),
    ]
