# Generated by Django 5.2.4 on 2025-09-12 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emissionfactor',
            name='scope',
        ),
        migrations.AddField(
            model_name='emissionfactor',
            name='applicable_scopes',
            field=models.JSONField(default=list, help_text='List of applicable GHG Protocol Scopes [1, 2, 3] where this factor can be used'),
        ),
        migrations.AlterField(
            model_name='emissionfactor',
            name='scope_3_category',
            field=models.CharField(blank=True, choices=[('purchased_goods_services', 'Purchased Goods and Services'), ('capital_goods', 'Capital Goods'), ('fuel_energy_related', 'Fuel and Energy Related Activities'), ('upstream_transport', 'Upstream Transportation and Distribution'), ('waste_generated', 'Waste Generated in Operations'), ('business_travel', 'Business Travel'), ('employee_commuting', 'Employee Commuting'), ('upstream_leased_assets', 'Upstream Leased Assets'), ('downstream_transport', 'Downstream Transportation and Distribution'), ('processing_sold_products', 'Processing of Sold Products'), ('use_sold_products', 'Use of Sold Products'), ('end_of_life_sold_products', 'End-of-life Treatment of Sold Products'), ('downstream_leased_assets', 'Downstream Leased Assets'), ('franchises', 'Franchises'), ('investments', 'Investments')], help_text='Specific Scope 3 category (required if any of applicable scopes is 3)', max_length=50, null=True),
        ),
    ]
