# Generated by Django 5.2.4 on 2025-08-27 10:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_project_last_modified'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='emissionscope',
            unique_together={('project', 'scope_number')},
        ),
        migrations.CreateModel(
            name='EmissionFactor',
            fields=[
                ('factor_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('category', models.CharField(choices=[('building_equipment', 'Building Equipment'), ('building_materials', 'Building Materials'), ('fuel', 'Fuel'), ('greenhouse_gases', 'Greenhouse Gases'), ('land_transport', 'Land Transport'), ('purchased_energy', 'Purchased Energy'), ('waste', 'Waste'), ('water', 'Water'), ('other', 'Other')], max_length=50)),
                ('sub_category', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('emission_factor_co2e', models.DecimalField(decimal_places=10, max_digits=15)),
                ('base_unit', models.CharField(max_length=100)),
                ('source', models.CharField(default='sefr', max_length=100)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('ghg_standard', models.CharField(blank=True, max_length=100, null=True)),
                ('ipcc_version', models.CharField(blank=True, max_length=20, null=True)),
                ('boundary_exclusions', models.TextField(blank=True, null=True)),
                ('gas_type', models.CharField(blank=True, max_length=20, null=True)),
                ('gwp_factor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('raw_emission_factor', models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True)),
                ('is_sefr_factor', models.BooleanField(default=True)),
                ('is_editable', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('name', 'category', 'sub_category', 'source')},
            },
        ),
        migrations.CreateModel(
            name='EmissionActivity',
            fields=[
                ('activity_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=15)),
                ('unit', models.CharField(max_length=50)),
                ('calculated_emissions', models.DecimalField(decimal_places=6, default=0, max_digits=15)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='api.project')),
                ('scope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='api.emissionscope')),
                ('emission_factor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='api.emissionfactor')),
            ],
        ),
    ]
