# Generated by Django 5.2.4 on 2025-11-24 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_lcaactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='emissionactivity',
            name='is_recurring',
            field=models.BooleanField(default=True, help_text='Whether this activity recurs regularly (e.g., monthly electricity)'),
        ),
        migrations.AddField(
            model_name='emissionactivity',
            name='period_end',
            field=models.DateField(blank=True, help_text='End of reporting period (e.g., 2024-01-31)', null=True),
        ),
        migrations.AddField(
            model_name='emissionactivity',
            name='period_start',
            field=models.DateField(blank=True, help_text='Start of reporting period (e.g., 2024-01-01)', null=True),
        ),
        migrations.AddField(
            model_name='lcaactivity',
            name='is_recurring',
            field=models.BooleanField(default=False, help_text='Whether this activity recurs (usually False for LCA products)'),
        ),
        migrations.AddField(
            model_name='lcaactivity',
            name='period_end',
            field=models.DateField(blank=True, help_text='End of reporting period', null=True),
        ),
        migrations.AddField(
            model_name='lcaactivity',
            name='period_start',
            field=models.DateField(blank=True, help_text='Start of reporting period', null=True),
        ),
    ]
