# Generated by Django 5.2.4 on 2025-09-01 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_emissionscope_unique_together_emissionfactor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emissionfactor',
            name='emission_factor_co2e',
            field=models.DecimalField(decimal_places=5, max_digits=15),
        ),
    ]
