# Generated by Django 5.2.4 on 2025-11-25 16:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_emissionactivity_is_recurring_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lcaproduct',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lcaproduct',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='ProductExchange',
            fields=[
                ('exchange_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the input', max_length=255)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=15)),
                ('unit', models.CharField(max_length=50)),
                ('calculated_impact', models.DecimalField(decimal_places=6, default=0, max_digits=15)),
                ('emission_factor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.emissionfactor')),
                ('input_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_in', to='api.lcaproduct')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchanges', to='api.lcaproduct')),
            ],
        ),
    ]
