# Generated by Django 5.2.4 on 2026-01-16 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_lcaproduct_description_lcaproduct_last_modified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emissionactivity',
            name='destination_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='emissionactivity',
            name='destination_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='emissionactivity',
            name='destination_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='emissionactivity',
            name='origin_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='emissionactivity',
            name='origin_location',
            field=models.CharField(blank=True, help_text='City, Country or Country Code', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='emissionactivity',
            name='origin_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='lcaactivity',
            name='destination_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='lcaactivity',
            name='destination_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lcaactivity',
            name='destination_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='lcaactivity',
            name='origin_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='lcaactivity',
            name='origin_location',
            field=models.CharField(blank=True, help_text='City, Country or BW2 Loc Code', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lcaactivity',
            name='origin_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='location',
            field=models.CharField(blank=True, help_text='Project location/HQ (City, Country)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
