# Generated by Django 5.2.4 on 2025-09-01 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_emissionfactor_emission_factor_co2e'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emissionfactor',
            name='emission_factor_co2e',
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
    ]
