# Generated by Django 5.2.4 on 2025-08-25 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_project_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='content',
            new_name='description',
        ),
    ]
