# Generated by Django 5.2.4 on 2025-09-03 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_emissionfactor_emission_factor_co2e'),
    ]

    operations = [
        migrations.AddField(
            model_name='emissionactivity',
            name='scope3_category',
            field=models.CharField(blank=True, choices=[('purchased_goods_services', '1. Purchased goods and services'), ('capital_goods', '2. Capital goods'), ('fuel_energy_related', '3. Fuel- and energy-related activities'), ('upstream_transport', '4. Upstream transportation and distribution'), ('waste_generated', '5. Waste generated in operations'), ('business_travel', '6. Business travel'), ('employee_commuting', '7. Employee commuting'), ('leased_assets_upstream', '8. Upstream leased assets'), ('downstream_transport', '9. Downstream transportation and distribution'), ('processing_sold_products', '10. Processing of sold products'), ('use_sold_products', '11. Use of sold products'), ('end_of_life', '12. End-of-life treatment of sold products'), ('leased_assets_downstream', '13. Downstream leased assets'), ('franchises', '14. Franchises'), ('investments', '15. Investments')], max_length=64, null=True),
        ),
    ]
