services:
  db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - PostgresData:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  django:
    image: python:3.10-slim
    container_name: django_server
    command: >
      sh -c "apt-get update &&
      apt-get install -y netcat-openbsd &&
      pip install -r requirements.txt &&
      while ! nc -z db 5432; do sleep 1; done &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DEBUG: "True"
      DB_NAME: ${DB_NAME}
      DB_USER: postgres
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: db
      DB_PORT: 5432
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    working_dir: /app

volumes:
  PostgresData:
